### ISSUE TITLE
Grouped animations take more than one frame to start

### ISSUE THREAD

**Issue by morethanreal** [web-animations/web-animations-next#260]
When you start a grouped animation, sometimes you see a frame of the "end state" before the animation starts.

**Comment by morethanreal** [comment]
It looks like the referenced PR is merged. Is this issue fixed and has it made into a release in web-animations-js?

**Comment by dstockwell** [comment]
@morethanreal I pushed a release that contains the fix: https://github.com/web-animations/web-animations-js/releases/tag/1.0.5

**Comment by morethanreal** [comment]
I can still reproduce the issue in Chrome 39. Can we reopen this?

**Comment by rjwright** [comment]
Yvonne does this happen in other browsers or only Chrome (with native fallback)? I'm wondering if it's related to https://github.com/web-animations/web-animations-next/issues/267, which I'm trying to pin down now.

**Comment by rjwright** [comment]
Hey @morethanreal , do you have a specific example where you can see this happening? I can't reproduce it.

**Comment by rjwright** [comment]
@morethanreal I just had  a look at http://jsbin.com/lawuli (sorry I didn't see it before! I don't know how I missed it). As someone else noticed, this is not a problem anymore in Chrome 41.

I'd still kinda like to know exactly what bug was causing it though. It could be related to https://github.com/web-animations/web-animations-next/issues/278.

**Comment by dstockwell** [comment]
Chrome 41 is stable.
